### ISSUE TITLE
Folders return same UIDValidity

### ISSUE THREAD

**Issue by MHuesler** [stalwartlabs/imap-server#10]
Some IMAP clients rely on a different UIDValidity value per folder to work. This value is often combined with the message index to create a unique message id per mailbox. When returning the same UIDValidity the logic breaks. 

Current behavior:
The IMAP server creates the same UIDValidity for all folders.

Desired behavior:
The IMAP server creates a different a UIDValidity per folder.

**Comment by mdecimus** [comment]
Hi @MHuesler , this has now been fixed in Stalwart IMAP v0.3.
