### ISSUE TITLE
[bug]: Opening different folders quickly in thunderbird results in "Login to server xxx with username failed"

### ISSUE THREAD

**Issue by vfosnar** [stalwartlabs/imap-server#12]
### What happened?

As the title says. The problem is not new, it happened in 4.2 already.

### How can we reproduce the problem?

I can reproduce the problem by doing the following steps:
- open thunderbird
- create ~5 folders
- switch between them

### Version

v0.5.x

### What database are you using?

PostgreSQL

### What blob storage are you using?

S3-compatible

### Where is your directory located?

SQL

### What operating system are you using?

Docker

### Relevant log output

```shell
There is no mention of a failed log-in in the logs, only SQL lookups of the user.

There is a single suspicious looking SMTP line in the logs from around when it happens, may be unrelated:
* BYE Server shutting down.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdecimus** [comment]
You are probably making too many requests which are being [rate limited](https://stalw.art/docs/imap/ratelimit).

**Comment by vfosnar** [comment]
Thank you <3, the concurrency limit is what causes the error. Maybe it would make sense to consider raising the default value from 4 to something larger.

**Comment by mdecimus** [comment]
Sure, the default has been increased to 6.
