### ISSUE TITLE
[bug]: SIEVE LOGOUT should respond with OK, not BYE

### ISSUE THREAD

**Issue by the-djmaze** [stalwartlabs/imap-server#14]
### What happened?

https://datatracker.ietf.org/doc/html/rfc5804#section-2.3
> The server MUST reply with an `OK` response.

### How can we reproduce the problem?

https://github.com/the-djmaze/snappymail/issues/1455

### Version

v0.6.x

**Comment by mdecimus** [comment]
That is incorrect. According to the ManageSieve grammar, both `OK, `NO` and `BYE` is a valid responses for the `LOGOUT` command:

```txt
    response-logout       = response-oknobye
    response-oknobye    = response-ok / response-nobye
    response-nobye        = ("NO" / "BYE") [SP "(" resp-code ")"]
                            [SP string] CRLF
                            ;; The string contains human-readable text
                            ;; encoded as UTF-8.
```

**Comment by the-djmaze** [comment]
I am correct. BYE is only valid for other cases.
See https://datatracker.ietf.org/doc/html/rfc5804#section-1.2

**Comment by stappersg** [comment]
And later there was [commit d94a6a2ec6d5f3](https://github.com/stalwartlabs/mail-server/commit/d94a6a2ec6d5f3b07d9e7868fb5f7bc6007e481c).
I did learn that from https://github.com/the-djmaze/snappymail/issues/1455#issuecomment-1966994327
