### ISSUE TITLE
[HELP] How to configure with SASL

### ISSUE THREAD

**Issue by mzch** [stalwartlabs/imap-server#4]
I tried stalward-jmap and stalward-imap server, these are great, thanks for your work!
But I have a few difficulities.
IMAP server works without problem. I can receive inbound mails and read them.
Next I'd like to configure Postfix server with SASL using `saslauthd` for sending a outbound mail.
I tried `saslauthd -a rimap -O localhost`, but authentications alwasy fail.
Could you advice me how to configure Postfix with SASL using Stalwart-Imap server?

**Comment by mdecimus** [comment]
Have you enabled TLS on your IMAP server? Probably Postfix is refusing to authenticate over plain text if TLS is unavailable.
Also, could you enable detailed logging for sslauthd so we see why it is failing?

**Comment by mzch** [comment]
Yes, I enabled TLS. In that case does Stalwar-IMAP server need STARTTLS by any chance? If so, I have to give up to usse it... `saslauthd` accepts only no-encrypted authentication.

**Comment by mzch** [comment]
Cyrus `saslauthd` tries IMAP login using `LOGIN` command, but Stalwart-IMAP server says, 'NO LOGIN is disabled on the clear-text port.' and doesn't accept `LOGIN` command, so authentication fails. Will you expand Stalwart-IMAP to accept `LOGIN` command?

**Comment by mdecimus** [comment]
Stalwart IMAP supports both LOGIN and PLAIN authentication over a TLS connection. You need to configure your SASL connector to either connect to the implicit TLS port or to upgrade the connection with STARTTLS.
Alternatively if SSL is not supported perhaps you can install a service to tunnel clear text into TLS?

**Comment by mzch** [comment]
Oh, is that so? I installed `stunnel` and authenticated successfully, Thanks @mdecimus !

**Comment by mzch** [comment]
I found `saslauthd` dropped a domain part of username. This is a problem of `saslauthd`. Thanks.

**Comment by mzch** [comment]
@mjac1521 If it's best there is such a way, but I think stalwart-imap server should have submission protocol proxy...

**Comment by mzch** [comment]
FYA:
- `/etc/postfix/main.cf`
```postfix
# SMTP Authentications
smtpd_sasl_auth_enable = yes
smtpd_sasl_type = cyrus
smtpd_sasl_path = smtpd
smtpd_sasl_security_options = noanonymous
…
# Transport
local_transport = local
virtual_mailbox_domains = hash:/etc/postfix/vdomains
virtual_transport = lmtp:inet:127.0.0.1:11200
fallback_transport = virtual
```
- `/etc/postfix/vdomains`
```
example.com     OK
example.net     OK
```
- `/etc/postfix/sasl/smtpd.conf`
```conf
pwcheck_method: saslauthd
mech_list: PLAIN LOGIN
```
- `/etc/stunnel/stunne.conf`
```ini
[imap]
client = yes
accept = 127.0.0.1:143
connect = your-mail-host.example.com:993
verifyChain = yes
CApath = /etc/ssl/certs
checkHost = your-mail-host.example.com
OCSPaia = yes
```
- `/etc/default/saslauthd`
```conf
MECHANISMS="rimap"
OPTIONS="-c -r -m /var/spool/postfix/var/run/saslauthd"
```

**Comment by mdecimus** [comment]
Thanks @mzch for the info. On the next release I'll add support for plain text authentication in case the connection comes from localhost.

**Comment by mdecimus** [comment]
Stalwart IMAP v0.3 now has an option to allow plain text authentication.
