### ISSUE TITLE
Unable move a mail to folders

### ISSUE THREAD

**Issue by mzch** [stalwartlabs/imap-server#5]
I can't move a mail from inbox to other folers.

Could you advice me what I should do?

- Client
1. OS: macOS `13.1`
2. MUA: Apple Mail.app `16.0`, Postbox `7.0.59`

- Server
1. OS: Debian `11.6`
2. Stalwart-JMAP: `0.2.0`
4. Stalwart-IMAP: `0.2.0`

- Stalwart-JMAP Log : log-level: `debug`
No output.
- Stalwart-IMAP Log: log-level : `debug`
See https://gist.github.com/mzch/2deade6aa90d38c652ab6ef34dfd3bee

**Comment by mdecimus** [comment]
Hi @mzch , thanks for the report!  I will look into this in a few weeks as soon as the SMTP server is released.

**Comment by MHuesler** [comment]
maybe related to #10
