### ISSUE TITLE
Allow to listen unencrypted to TLS port and behave as if the transport was encrypted

### ISSUE THREAD

**Issue by mildred** [stalwartlabs/imap-server#7]
In order to manage encryption at a reverse-proxy layer, it would be nice to allow the tls port to listen unencrypted but behaves as if it was encrypted and provide PLAIN login... This would need to be set up specially and a specific bind address might be useful to have port 143 listen to 0.0.0.0 and tls encrypted only to 127.0.0.1

This is not strictly required, a self signed certificate could be set up with the reverse proxy ignoring the backend certificate.

**Comment by mdecimus** [comment]
Stalwart IMAP v0.3 now has an option to allow plain text authentication on an unencrypted port.
